# Generated by Django 4.2.7 on 2023-12-01 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("fragma", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cadastro",
            name="senha",
            field=models.CharField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cadastro",
            name="nome",
            field=models.CharField(max_length=100),
        ),
    ]
