# Generated by Django 4.2.7 on 2023-12-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fragma", "0002_cadastro_senha_alter_cadastro_nome"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cadastro",
            name="senha",
        ),
        migrations.AddField(
            model_name="cadastro",
            name="chave",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cadastro",
            name="doar",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cadastro",
            name="nome",
            field=models.CharField(max_length=255),
        ),
    ]
